export type Doctor = { id:string; name:string; specialty:string; experience:string; rating:number; reviews:number; fee:number; location:string; hospital:string; availability:string[]; initials:string; bio:string; qualifications:string[]; specializations:string[] };
export const doctors: Doctor[] = [
{id:'maya-shah',name:'Dr. Maya Shah',specialty:'Cardiology',experience:'14 years',rating:4.9,reviews:184,fee:900,location:'Lucknow',hospital:'Harborview Medical Center',availability:['09:30 AM','11:00 AM','02:30 PM','05:00 PM'],initials:'MS',bio:'Board-certified cardiologist focused on preventive heart health, hypertension and evidence-led cardiac care.',qualifications:['MBBS, King’s College Medical School','MD, Internal Medicine','DM, Cardiology'],specializations:['Preventive cardiology','Hypertension','Heart rhythm care']},
{id:'aarav-mehta',name:'Dr. Aarav Mehta',specialty:'Dermatology',experience:'11 years',rating:4.8,reviews:129,fee:750,location:'Lucknow',hospital:'Bluecrest Clinic',availability:['10:00 AM','12:30 PM','04:00 PM'],initials:'AM',bio:'Dermatologist specializing in acne, sensitive skin and practical long-term skincare plans.',qualifications:['MBBS','MD, Dermatology'],specializations:['Acne & scarring','Sensitive skin','Clinical dermatology']},
{id:'neha-iyer',name:'Dr. Neha Iyer',specialty:'Pediatrics',experience:'12 years',rating:4.9,reviews:211,fee:700,location:'Lucknow',hospital:'Riverside Children’s Hospital',availability:['09:00 AM','11:30 AM','03:00 PM','06:00 PM'],initials:'NI',bio:'Warm, family-centered pediatrician supporting children from newborn care through adolescence.',qualifications:['MBBS','DCH, Pediatrics'],specializations:['Newborn care','Child development','Vaccination guidance']},
{id:'kabir-verma',name:'Dr. Kabir Verma',specialty:'Orthopedics',experience:'16 years',rating:4.7,reviews:96,fee:850,location:'Lucknow',hospital:'Northstar Orthopedic Institute',availability:['08:30 AM','01:00 PM','04:30 PM'],initials:'KV',bio:'Orthopedic specialist with a focus on sports injuries, joint health and mobility-focused rehabilitation.',qualifications:['MBBS','MS, Orthopedics','Fellowship, Sports Medicine'],specializations:['Sports injuries','Joint pain','Rehabilitation']},
{id:'sana-kapoor',name:'Dr. Sana Kapoor',specialty:'Neurology',experience:'13 years',rating:4.8,reviews:118,fee:1000,location:'Lucknow',hospital:'Harborview Medical Center',availability:['10:30 AM','01:30 PM','05:30 PM'],initials:'SK',bio:'Neurologist caring for migraine, sleep-related neurological concerns and general adult neurology.',qualifications:['MBBS','MD, Medicine','DM, Neurology'],specializations:['Migraine care','Sleep neurology','Adult neurology']},
{id:'rohan-bose',name:'Dr. Rohan Bose',specialty:'ENT',experience:'9 years',rating:4.6,reviews:82,fee:650,location:'Lucknow',hospital:'Bluecrest Clinic',availability:['09:30 AM','12:00 PM','03:30 PM','06:30 PM'],initials:'RB',bio:'ENT physician providing practical care for sinus, ear, throat and voice concerns.',qualifications:['MBBS','MS, ENT'],specializations:['Sinus care','Ear health','Voice & throat']},
];
export const specialties=[
['Cardiology','Heart and circulatory health, prevention and ongoing cardiac care.','HeartPulse'],['Dermatology','Expert care for skin, hair and nail concerns.','SkinWell'],['Neurology','Specialist support for the brain, nerves and neurological health.','NeuroCare'],['Orthopedics','Mobility, joint, bone and sports injury care.','MotionLab'],['Pediatrics','Thoughtful healthcare for infants, children and teens.','LittleSteps'],['Gynecology','Women’s health and preventive care across every life stage.','Bloom Women’s'],['Ophthalmology','Comprehensive eye health and vision services.','ClearView'],['ENT','Care for ear, nose, throat and related conditions.','HearWell']
].map(([name,description,focus],i)=>({id:name.toLowerCase(),name,description,focus,index:i}));
export const hospitals=[
{name:'Harborview Medical Center',location:'Gomti Nagar, Lucknow',specialties:['Cardiology','Neurology','Orthopedics'],facilities:['24/7 emergency','Diagnostics','Pharmacy'],tag:'Multi-specialty'},
{name:'Bluecrest Clinic',location:'Hazratganj, Lucknow',specialties:['Dermatology','ENT','Gynecology'],facilities:['Digital records','Lab services','Day care'],tag:'Specialty clinic'},
{name:'Riverside Children’s Hospital',location:'Indira Nagar, Lucknow',specialties:['Pediatrics','Ophthalmology'],facilities:['Child-friendly wards','Diagnostics','Vaccination center'],tag:'Children’s care'},
{name:'Northstar Orthopedic Institute',location:'Aliganj, Lucknow',specialties:['Orthopedics','Sports medicine'],facilities:['Physiotherapy','Imaging','Rehab gym'],tag:'Orthopedic center'},
];
export const articles=[['A practical guide to preparing for your first doctor visit','Simple steps to make a routine consultation more useful.'],['Understanding preventive heart health','Everyday habits and routine checkups that support cardiovascular health.'],['How to build a calmer bedtime routine','Small changes that can make sleep routines more consistent.']];
